sudo: required
services:
  - docker

before_install:
  - docker build amartynyshyn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amartynyshyn/react-test npm test

after_success:
  - docker build -t amartynyshyn/multi-client ./client
  - docker build -t amartynyshyn/multi-nginx ./nginx
  - docker build -t amartynyshyn/multi-server ./server
  - docker build -t amartynyshyn/multi-worker ./worker
  #login to docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push amartynyshyn/multi-client
  - docker push amartynyshyn/multi-nginx
  - docker push amartynyshyn/multi-server
  - docker push amartynyshyn/multi-worker
